image: python:latest
pages:
  stage: deploy
  only:
    - main
  script:
    - pip install mkdocs-material
    - mkdocs build --site-dir public-doc
  artifacts:
    paths:
      - public-docs