## https://squidfunk.github.io/mkdocs-material/

# Site Information
site_name: Containers
site_url: https://pedrolsazevedo.github.io/containers/
site_description: Conjunto de materias e modelos para aprendizado de containers.
site_author: Pedro Luis Silva Azevedo

# Git Repo
repo_name: containers
repo_url: https://github.com/pedrolsazevedo/containers/
edit_uri: edit/main/docs/

# Configuration
strict: false
use_directory_urls: true
docs_dir: docs
site_dir: public
dev_addr: 0.0.0.0:8000

# Documentation & Theme
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.share 
    - content.code.annotate
#  locale: en
  language: pt-BR
extra:
  version:
    tag: v0.0.13
    provider: pedrolsazevedo

# Extensions and Plugins
markdown_extensions:
  - toc:
      permalink: true

  - codehilite
  - admonition
  - attr_list
  - md_in_html

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
        anchor_linenums: true
        auto_title: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg




plugins:
  - git-revision-date
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      indexing: 'full'
      lang:
         - pt-BR
  - markdownextradata: {}

# Navigation and Content
nav:
  - index.md
  - Estudos:
    - "Cursos": estudos/cursos.md
    - "Materiais": estudos/materiais.md
  - Kubernetes:
    - Modelos: 
      - kubernetes/index.md
      - "Wordpress": "kubernetes/modelos/wordpress/index.md"
