name: ci 
on:
  label:
    types:
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material \
             mkdocs-git-revision-date-plugin \
             mkdocs-git-revision-date-localized-plugin \
             mkdocs-markdownextradata-plugin \
             git+https://github.com/sebastienwarin/mkdocs-mermaid-plugin \
             mkdocs[i18n]
      - run: mkdocs gh-deploy --force
